export default {
	arrowTop: 'icon-arrow-top',
	arrowRight: 'icon-arrow-right',
	arrowDown: 'icon-arrow-down',
	arrowLeft: 'icon-arrow-left',

	empty: 'icon-empty',
	home: 'icon-home',
	info: 'icon-info',
	github: 'icon-github',
	msgBoard: 'icon-msg_board',
	mail: 'icon-mail',
	warn: 'icon-warn',
	success: 'icon-success',
	wechart: 'icon-wechart',
	qq: 'icon-qq',
	project: 'icon-project',
	aboutMe: 'icon-about_me',
	article: 'icon-article',
	close: 'icon-close',
	error: 'icon-error',

	notes: 'icon-notes',
	write: 'icon-write',
	code: 'icon-code',
};